
  CREATE TABLE "MONITOR_TABMAG_ABILITATI" 
   (	"IDTABMAG" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"CODICEMAG" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"DESTABMAG" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"IDTABMAGDOC" VARCHAR2(10 BYTE), 
	"MAGLAVORAZIONESN" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"MAGLAVTERZISN" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"MAGVENDIBILESN" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"MAGPROVINCIA" VARCHAR2(2 BYTE), 
	"COSTOMEDIOSN" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"COSTOULTIMOSN" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"FABBISOGNISN" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"MAGPALLETTIZZATOSN" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATASTAMPAGIORNALE" DATE, 
	"ANNORIMANENZAINIZ" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"DATACR" DATE, 
	"DATAVR" DATE, 
	"UTENTE" VARCHAR2(10 BYTE), 
	"CODICECLIFOSN" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"IDTABMAGLISVEN" VARCHAR2(10 BYTE), 
	"IDTABMAGLAVEST" VARCHAR2(10 BYTE), 
	"CIS_INVENTORYID" VARCHAR2(25 BYTE), 
	"CIS_ALTINVENTORYID" VARCHAR2(25 BYTE), 
	"STATOINTRA" CHAR(2 BYTE), 
	"PREUSCITASN" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"SOSPESOSN" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"SCARTOSN" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"IDTABMAGEXIT" VARCHAR2(10 BYTE), 
	"IDTABMAG_SOS" VARCHAR2(10 BYTE), 
	"IDTABMAG_SCA" VARCHAR2(10 BYTE), 
	"IDTABMAG_STOCK" VARCHAR2(10 BYTE), 
	"PRELIEVO_SN" NUMBER(*,0), 
	"ESTERNO_SN" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"TRANSITO_SN" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"AFFIDABILITA" NUMBER(*,0) DEFAULT 0
   ) ;
   
   
  CREATE UNIQUE INDEX "TABMAG_PK2" ON "MONITOR_TABMAG_ABILITATI" ("CODICEMAG") ;



--UPDATE MONITOR_TABMAG_ABILITATI SET codicemag = replace(codicemag,'COMF','CONF'),DESTABMAG = replace(DESTABMAG,'COMF','CONF') where codicemag like 'COMF%';
